SWIFT-729: Update issue templates
mongodb/mongo-swift-driver pull request #710
Opened 2021-11-18 18:39 UTC by bajanam

This migrates our legacy issue template to the new template   format, minor clean up.  Pending Further clean up clarifications.

2021-11-18 21:55 UTC, kmahar requested changes
some suggestions for things to condense/cut

2021-11-18 21:55 UTC, kmahar commented on .github/ISSUE_TEMPLATE/bug_report.md
> +  If possible, try to determine if the bug is actually part of the Swift driver,
let's remove this line, I think it's a lot easier for us to determine this than for a user.

2021-11-18 21:55 UTC, kmahar commented on .github/ISSUE_TEMPLATE/bug_report.md
> +
I'd suggest we condense the following items into something shorter, like

1. What version of Swift are you using? (Run `swift --version`)
2. What operating system are you using? (Run `uname -a`)
3. What versions of the driver and its dependencies are you using? (Run `swift package show-dependencies`)
4. What version of MongoDB are you using? (Check with the MongoDB shell using `db.version()`) 
5. What is your MongoDB topology (standalone, replica set, sharded cluster, serverless)?

2021-11-18 21:55 UTC, kmahar commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**Screenshots**
let's remove this. id rather people give us code samples

2021-11-18 21:55 UTC, kmahar commented on .github/ISSUE_TEMPLATE/bug_report.md
> +* Is there a workaround that seems to avoid this this issue?
let's remove this and the next bullet, I dont think they are very helpful to us

2021-11-18 21:55 UTC, kmahar commented on .github/ISSUE_TEMPLATE/bug_report.md
> +* If you know how to reproduce the bug, use the `BugReport` project in our
let's change to "If you know how to reproduce this bug, please include a code snippet here:"

2021-11-29 18:35 UTC, bajanam reviewed
Updates made

2021-11-30 20:16 UTC, kmahar approved these changes
lgtm, thanks! adding in Patrick and Isabel

2021-11-30 22:13 UTC, isabelatkinson approved these changes

2022-01-04 19:43 UTC, patrickfreed approved these changes
LGTM!

2022-01-06 16:36 UTC, merged